version: '3.8'

services:
  roadtopiris-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roadtopiris-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Mapear assets estáticos del proyecto
      - ./proyectdata:/app/proyectdata:ro
      - ./roadtopiris-web/public/assets:/app/public/assets:ro
      - logs:/app/logs
    networks:
      - roadtopiris-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx como reverse proxy
  nginx:
    image: nginx:alpine
    container_name: roadtopiris-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proyectdata:/usr/share/nginx/html/proyectdata:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      roadtopiris-web:
        condition: service_healthy
    networks:
      - roadtopiris-network
    restart: unless-stopped

networks:
  roadtopiris-network:
    driver: bridge

volumes:
  logs:
    driver: local
  nginx-logs:
    driver: local
