FROM node:18-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar código fuente
COPY . .

# Exponer puerto
EXPOSE 3000

# Configurar variables de entorno
ENV HOST=0.0.0.0
ENV PORT=3000

# Comando para desarrollo
CMD ["npm", "start"]
